### ISSUE TITLE
mouse interaction broken

### ISSUE THREAD

**Issue by genekogan** [therewasaguy/p5js-webIDE#2]
mouseX / mouseY is broken, possibly because the sketch is behind an iframe.

**Comment by therewasaguy** [comment]
looks like this has to do with the z-index of the iframe, and the fact that the iframe is not focused. I tried focusing it every time it loads, and changing the z-index. These things work, but if the editor or other div in front of the iframe (as they need to be in order to see them in front of a fullscreen sketch), then they will block mouse events. The ace editor in particular will catch events.

We can pass events to the iframe from the parent window by adding this script to the iframe (for now I'm putting it in debug-console.js). So far it seems to be working, though I worry it may be inefficient to clone the entire event object every time mouse is moved.

```
  // catch key and mouse events, inspired by http://stackoverflow.com/a/16914658/2994108
  var eventsToCatch = ['keyup', 'keydown', 'keypress',
  'mouseup', 'mousedown', 'mousemove', 'click', 'mouseenter', 'mouseleave', 'mouseover', 'mouseout',
  'touchstart', 'touchend', 'touchcancel', 'touchleave', 'touchmove'];

  for (var i = 0; i < eventsToCatch.length; i++) {
    var evt = eventsToCatch[i];
    parent.document.body.addEventListener(evt, catchEvent);
  }

  function catchEvent(e) {
    var ev = document.createEvent('Event');
    ev.initEvent(e.type, true, false);
    for (var key in e) {
        // we dont wanna clone target and we are not able to access "private members" of the cloned event.
        if (key[0] == key[0].toLowerCase() && ['__proto__', 'srcElement', 'target', 'toElement'].indexOf(key) == -1) {
            ev[key] = e[key];
        }
    }
    document.dispatchEvent(ev);
  }
```
