### ISSUE TITLE
The numbers infront of examples should not be there and are in alphabetical order?

### ISSUE THREAD

**Issue by raminie** [therewasaguy/p5js-webIDE#37]

**Comment by therewasaguy** [comment]
thanks for this issue, @raminie!

I've added more friendly example names and here's how I approached it:
 https://github.com/therewasaguy/p5js-webIDE/commit/e3346c7b9c7b2c9ced725bd6a1c3fda9a9b5b261

Will probably revisit this soon because the examples should also be linked to project ID's in the database.
