### ISSUE TITLE
Run delay

### ISSUE THREAD

**Issue by shiffman** [therewasaguy/p5js-webIDE#67]
Some of the time there is a long delay before changes are reflected in the sketch when hitting the run button.  There seems to be some server side call that is happening.

**Comment by therewasaguy** [comment]
Looking into this, it is making a server side call because hitting the run button refreshes an iframe. The iframe is an empty html page ("output.html") with a tiny script ("debug-console.js") that sends debugging messages to the parent window.

I've experimented with caching and gzip compression and it seems to have made a difference.

It also seems that using a view engine on the server is causing some delay, even though output.html is rendered static, without the view engine. Jade in particular is the slowest view engine. We're only really making use of it in viewproject.jade where the project contents are passed in as variables, and view in particular takes a long time to load. We could use a different view engine, or fetch project contents with ajax while the project displays a loading screen.

To do:
- [ ] minify debug-console.js and inject it into output.html (i.e. using gulp-inject)
- [ ] try view engine alternatives ([dot](http://olado.github.io/doT/index.html)) or a better way to render viewproject

**Comment by therewasaguy** [comment]
The delay is much better for in-page sketches, though it could always be faster...! I'll make new issues for the other two items
