### ISSUE TITLE
Creating moving square killed the program

### ISSUE THREAD

**Issue by tarmokorela** [therewasaguy/p5js-webIDE#83]
Cannot load either my own or other works anymore in p5.js.

<img width="1239" alt="screen shot 2016-01-05 at 20 12 17" src="https://cloud.githubusercontent.com/assets/16547311/12132456/aa4aa81a-b3e9-11e5-8a9c-9b21b3883505.png">
<img width="1252" alt="screen shot 2016-01-05 at 20 16 55" src="https://cloud.githubusercontent.com/assets/16547311/12132457/aa4c7424-b3e9-11e5-968a-e66841b1ef09.png">

**Comment by therewasaguy** [comment]
Thanks for reporting this issue and for including screenshots!

It seems like this issue is related to webgl mode. Check out the p5 documentation for sphere:
http://p5js.org/reference/#/p5/sphere. Its second parameter is "detail" and it says "avoid detail above 150, it may crash the browser".

I was able to get it to work by removing that second parameter from the `sphere`
http://p5ide.herokuapp.com/editor#?sketch=568c71899144350300ab21c5
