### ISSUE TITLE
new tab should use custom dialog, not browser prompt

### ISSUE THREAD

**Issue by shiffman** [therewasaguy/p5js-webIDE#96]
The new tab (`+`) was not working for me in class.  The students also reported it not working.  Strangely it is now working for me.   I'll try to see if I can pinpoint / see what is going on.

**Comment by therewasaguy** [comment]
New Tab is still using a browser prompt, instead of the customized dialog/modal. So if a user checked the button to "prevent this page from opening additional dialogs" they will no longer be able to add tabs. I'll change this issue title to "New Tabs should use the dialog module, not browser prompt"
